script: bundle exec rake validate && bundle exec rake lint && bundle exec rake spec
  SPEC_OPTS='--format documentation'
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.0"
notifications:
  email: false
deploy:
  provider: puppetforge
  user: CERNOps
  password:
    secure: "laCSB2PkNsmHbIV9lK6qoaRciBd75b4IHveX8qHGdEKCT+Tyj26vS8f7CfAGqhq3IqQYJnTQFH5F/sByi/HqR1owcIjl64djDfYiACRoZyMQaSPd+j3q3x9q+HOv1AJFyn8cyqZFg3uRB7tFcWV31hd8I86wa4KitlFwoUTZkE0rLjKDglnnNmmuOX9mj6uqqgkrPXdcinU0fI6q9Vh7kMsg8GDTD7zSbFe1KdDq9L94dm8bD10391wTe5wfwwTjZF/oGbAnV/1y6pFRm9a19cEP4ScXT3Qph78+APOC0KOrnbWn9GKEzIzjldOCS5x5GzzgyDovkklvRtq4oyjxgm3pfDR6RKMb0PeXCdLPd1aNCVovSR56HcxDNglcUmcGUTHMiEw0GS0dIgLI3mlKCCZNuIwKgD+LWU+UYovkmyFdHUIqqE6pLKeGgzdBYKy2FIWYevdZrlSbuUnRSF6rTs2sNIzqyaBnYYhieA5oarn2Pt4abuQwuKaNnzSGpu+ng1BWEmeca4rB1Q9RGnxYPLsdMjPs3jcamsrJRiXGqAG2yD0akQrxgQy8G4Wis7vG2Z3ZL5DgFjzR6huMCtybQLOLSTGiaBmO8+MxLSmJsmnCqFI6T/T9lQLGgiwTNzz/X7doOotOLIdlt6fmT5OwOMUID14vm+l1ITJpcI+WAZM="
  on:
    tags: true
    all_branches: true
    rvm: 1.9.3
    condition: $FUTURE_PARSER = yes


